services:

  nginx:
    build:
      context: .
      dockerfile: nginx.debug.Dockerfile
    ports:
      - 1935:1935
      - 80:80
      - 443:443
    volumes:
      - ./etc/openssl:/etc/ssl
      - ./hls:/etc/hls
    environment:
      - PUBLIC_IP=${PUBLIC_IP}
      - TWITCH_KEY=${TWITCH_KEY}
      - YOUTUBE_KEY=${YOUTUBE_KEY}
    restart: always